# Generated by Django 2.2.4 on 2021-09-23 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tee',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tees', to='golfapp.Hole'),
        ),
    ]
