# Generated by Django 2.2.4 on 2021-09-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0002_auto_20210922_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='tee_colors',
            field=models.ManyToManyField(related_name='tees', to='golfapp.TeeColor'),
        ),
    ]
