# Generated by Django 2.2.4 on 2021-09-25 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0003_tee_tee_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tee',
            name='tee_colors',
        ),
        migrations.AddField(
            model_name='tee',
            name='tee_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tees', to='golfapp.TeeColor'),
            preserve_default=False,
        ),
    ]
