# Generated by Django 2.2.4 on 2021-09-25 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0004_auto_20210924_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tee',
            name='hole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tees', to='golfapp.Hole'),
        ),
    ]
