# Generated by Django 2.2.4 on 2021-09-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0005_auto_20210924_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tee',
            name='color',
        ),
    ]
