# Generated by Django 2.2.4 on 2021-09-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0006_remove_tee_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tee_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='golfapp.TeeColor'),
        ),
    ]
