# Generated by Django 2.2.4 on 2021-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0008_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Title this round (optional)'),
        ),
    ]
