# Generated by Django 2.2.4 on 2021-09-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0010_auto_20210928_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title this round (optional)'),
        ),
    ]
